module Views.Posts where

import Html exposing (Html, text, h1, div)
import UI


view: UI.Screen
view = UI.genericView "Posts" content



-- posts
content: List Html
content =
    [ h1 [] [text "Posts"]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    ]

