module Content.Posts where

import Html exposing (Html, text, h1, div)
import UI

screen: UI.Screen
screen ui =
    { header = []
    , content = view
    , footer = UI.footer
    }


-- posts
view: List Html
view =
    [ h1 [] [text "Posts"]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    , div [] [ text "aaaa" ]
    ]

